language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
matrix:
  include:
    # Spark 1.3.0
    - jdk: openjdk6
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.3.0"
    - jdk: openjdk6
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.3.0"
    # Spark 1.4.1
    - jdk: openjdk6
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.4.1"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.4.1"
    # Spark 1.5.0
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.5.0"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.5.0"
    # Spark 1.6.0
    - jdk: openjdk7
      scala: 2.10.5
      env: TEST_SPARK_VERSION="1.6.0"
    - jdk: openjdk7
      scala: 2.11.7
      env: TEST_SPARK_VERSION="1.6.0"
script:
  - sbt -Dspark.testVersion=$TEST_SPARK_VERSION ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION "test:scalastyle"
  - sbt ++$TRAVIS_SCALA_VERSION mima-report-binary-issues
after_success:
  - bash <(curl -s https://codecov.io/bash)
